export const EstadoPedido = {
  PENDIENTE: 'PENDIENTE',
  CONFIRMADO: 'CONFIRMADO',
  PREPARANDO: 'PREPARANDO',
  LISTO: 'LISTO',
  EN_CAMINO: 'EN_CAMINO',
  RECHAZADO: 'RECHAZADO',
}

export const MetodoPago = {
  EFECTIVO: 'EFECTIVO',
  TRANSFERENCIA: 'TRANSFERENCIA',
  PAGO_LINEA: 'PAGO_LINEA',
}

export const EstadoPago = {
  PENDIENTE: 'PENDIENTE',
  PENDIENTE_VERIFICACION: 'PENDIENTE_VERIFICACION',
  APROBADO: 'APROBADO',
  RECHAZADO: 'RECHAZADO',
}